services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app:/app/apps
      - DOCKER_ENV=1
    env_file:
      - .env.docker
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3
  