# Generated by Django 5.0.9 on 2026-02-20 18:55

import apps.authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('first_attempt', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP Rate Limit',
                'verbose_name_plural': 'OTP Rate Limits',
                'indexes': [models.Index(fields=['email', 'ip_address'], name='authenticat_email_d3ffc6_idx'), models.Index(fields=['blocked_until'], name='authenticat_blocked_46dcda_idx')],
                'unique_together': {('email', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=apps.authentication.models.user_avatar_path)),
                ('google_picture_url', models.URLField(blank=True, help_text='Original Google profile picture URL', null=True)),
                ('bio', models.TextField(blank=True, help_text='User biography', max_length=500, null=True)),
                ('location', models.CharField(blank=True, help_text='User location', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text='User website', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='authenticat_email_9cfae5_idx'), models.Index(fields=['user', 'is_verified'], name='authenticat_user_id_e55651_idx')],
            },
        ),
    ]
