name: Code & Template Formatting

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the PR branch (full history isn’t strictly needed
      #    since we’re not committing from here, but you can do fetch-depth: 0)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2️⃣ Format all your .py files with Black
      - name: Set up Python & run Black
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install black
          black .

      # 3️⃣ Prettier on your templates — no node_modules cleanup, no commit
      - name: Run Prettier on HTML/CSS/JS
        uses: creyD/prettier_action@v4.5
        with:
          file_pattern: |
            **/*.html
            **/*.css
            **/*.js
          prettier_options: --write
          clean_node_folder: false   # ◀ disable any node_modules deletion
          no_commit: true            # ◀ skip Prettier’s git commit/push

      # 4️⃣ Create (or update) a PR with *all* of Black’s and Prettier’s changes
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply Black & Prettier formatting"
          branch: formatting-fixes
          title: "Automated formatting fixes"
          body: |
            This PR runs:
            - Black on all Python files  
            - Prettier on HTML, CSS & JS templates  
