name: Debug & Auto-Format Code

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  debug-and-format:
    runs-on: ubuntu-latest

    steps:
      # ——————————————
      # 1️⃣ CHECKOUT
      # ——————————————
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # ensure we can push back later
          persist-credentials: true
          # bring full history if you ever need to commit
          fetch-depth: 0

      # ——————————————
      # 2️⃣ DEBUG: confirm workflow file
      # ——————————————
      - name: List workflow files
        run: ls -R .github/workflows

      - name: Show prettier.yml
        run: sed -n '1,200p' .github/workflows/prettier.yml || echo "prettier.yml not found"

      # ——————————————
      # 3️⃣ DEBUG: inspect Git state
      # ——————————————
      - name: Debug Git state
        run: |
          echo "=== Git environment variables ==="
          echo "GITHUB_REF       = $GITHUB_REF"
          echo "GITHUB_HEAD_REF  = ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF  = ${{ github.base_ref }}"
          echo
          echo "=== git status & branches ==="
          git status
          git rev-parse --abbrev-ref HEAD || true
          git branch -avv
          echo
          echo "=== git remotes ==="
          git remote -v

      # ——————————————
      # 4️⃣ FORMAT PYTHON
      # ——————————————
      - name: Set up Python and run Black
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install & run Black
        run: |
          pip install black
          black .

      # ——————————————
      # 5️⃣ FORMAT TEMPLATES WITH PRETTIER (ditch the action)
      # ——————————————
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Prettier
        run: npm install --no-save prettier
      - name: Prettify HTML/CSS/JS
        run: npx prettier --write "**/*.{html,css,js}"

      # ——————————————
      # 6️⃣ PUSH ALL CHANGES BACK
      # ——————————————
      - name: Commit & push formatting changes
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply Black & Prettier formatting"
          branch: ${{ github.head_ref }}
          skip_checkout: true
          token: ${{ secrets.GITHUB_TOKEN }}
