name: Auto Format Code with Black & Prettier

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  autoformat:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the PR’s branch (with credentials so we can push back)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2️⃣ Run Black over all your Python files
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install and run Black
        run: |
          pip install black
          black .

      # 3️⃣ Install Prettier (no package-lock, no node_modules cleanup)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Prettier
        run: npm install --no-save prettier

      # 4️⃣ Format your HTML, CSS & JS files
      - name: Prettify HTML/CSS/JS
        run: npx prettier --write "**/*.{html,css,js}"

      # 5️⃣ Commit & push *all* formatting changes back to the head branch
      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply Black & Prettier formatting"
          branch: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
