name: Run Sisimpur Brain Script

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust if needed

      - name: Run Sisimpur Brain script
        working-directory: sisimpur-brain
        run: |
          echo "Creating virtual environment..."
          python -m venv venv
          source venv/bin/activate

          echo "Installing requirements..."
          pip install --upgrade pip
          pip install -r requirements.txt

          echo "Running script..."
          # ✅ Explicitly set the env variable on the same line
          GOOGLE_API_KEY="${GOOGLE_API_KEY}" python main.py test_data/1_bangla.jpg
        env:
          # ✅ Makes secret available to the shell above
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
